name: PyTest

on:
  push:
    branches:
    - main
  pull_request:
    types:
      - opened
      - synchronize

# Run pytest on ubuntu, mac and windows

jobs:
  pytest:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - run: pip install -r requirements.txt

      - name: pytest
        run: |
          python -m pytest -vv .