name: Pytest slow nightly

# Run every day at 00:00 EST

on:
  workflow_dispatch:
    


jobs:
  pytest-slow:
    strategy:
      max-parallel: 1
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with: 
          ref: main

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: requirements.txt

      - name: Install dependencies within the environment
        run: pip install -r requirements.txt

      - name: pytest
        run: |
          python -m pytest -s -vv -m "slow" .